import { Button, VerticalBox, GridBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {

    in property <string> ausgabe: "";
    callback userInput(string);

    GridLayout {
        padding: 50px;
        spacing: 25px;
        Row {
            Text {
                horizontal-alignment: center;
                text: "Hello World";
                font-size: 60px;
                font-weight: 16;
            }
        }
        Row {
            input := LineEdit {
                text: "Hier Text eingeben";
                horizontal-alignment: center;
            }
        }
        Row {
            Button {
                text: "Text anzeigen";
                primary: true;
                clicked => { userInput(input.text) }
                }
            }
        Row {
            VerticalBox {
                Rectangle {
                    height: 100px;
                    background: #f2f2f2;
                    Text {
                        color: black;
                        font-size: 16px;
                        font-weight: 500;
                        text: root.ausgabe;
                    }
                }
            }
        }
    }
}
